/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    MainNotification: typeof import('./src/components/MainNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaComponent: typeof import('./src/components/TabelaComponent.vue')['default']
    TitleComponent: typeof import('./src/components/TitleComponent.vue')['default']
  }
}
