/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardDepartamento: typeof import('./src/components/departamento/cardDepartamento.vue')['default']
    CriarDepartamentoComponent: typeof import('./src/components/departamento/CriarDepartamentoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaDepartamentoComponent: typeof import('./src/components/departamento/TabelaDepartamentoComponent.vue')['default']
  }
}
