/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardDepartamento: typeof import('./src/components/departamento/cardDepartamento.vue')['default']
    CriarDepartamentoComponent: typeof import('./src/components/departamento/CriarDepartamentoComponent.vue')['default']
    EditarDepartamento: typeof import('./src/components/departamento/EditarDepartamento.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    MainNotification: typeof import('./src/components/MainNotification.vue')['default']
    RelatorioComponent: typeof import('./src/components/departamento/RelatorioComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaComponent: typeof import('./src/components/TabelaComponent.vue')['default']
    TabelaDepartamentoComponent: typeof import('./src/components/departamento/TabelaDepartamentoComponent.vue')['default']
    TabelaUsuario: typeof import('./src/components/usuario/TabelaUsuario.vue')['default']
    TitleComponent: typeof import('./src/components/TitleComponent.vue')['default']
  }
}
